; Максимальный размер загружаемого файла
upload_max_filesize = 150M
post_max_size = 150M

; Ограничение памяти на скрипт
memory_limit = 256M

; Время выполнения скрипта
max_execution_time = 300
max_input_time = 300

; Остальные стандартные настройки
file_uploads = On
